### ISSUE TITLE
cracked and mossy stone brick recipes switched?

### ISSUE THREAD

**Issue by ariehkovler** [gmlaxfanatic/FactoryMod#17]
Reported via modmail:

"Just finally harvested about 3 stacks of vines to make mossy stone bricks. Put my 32 lapis, 64 stone brick, and 64 vine in the chest, set factory to mossy stone recipe and activated the factory. Shortly thereafter, I opened my chest to find 64 cracked stone bricks. I found this quite strange and decided to experiment with putting in 32 lapis, 64 stone brick, and 64 flint set to the cracked stone brick recipe. This testing resulted in 64 mossy stone brick. The chiseled recipe with gravel seems to be working fine, however the output from the other two seems to be reversed."

**Comment by gmlaxfanatic** [comment]
Thanks for the report, I'll try to get this fixed tonight.
