### ISSUE TITLE
Gold ore in ore smelter

### ISSUE THREAD

**Issue by ghost** [gmlaxfanatic/FactoryMod#18]
32 -> 224? Is that a typo or is the 600% efficiency gain from smelting intended

**Comment by gmlaxfanatic** [comment]
That was recently implemented to compensate for the unintended gold scarcity.  I posted about it here: http://www.reddit.com/r/Civcraft/comments/1ff1po/suggestion_for_next_round_of_factorymod_factories/

Do you think it is a balanced change or is it too extreme?
