### ISSUE TITLE
ore smelter

### ISSUE THREAD

**Issue by thesnaake** [gmlaxfanatic/FactoryMod#4]
I just loaded this on my server to do some testing.  I tried to create an ore smelter, but when I go to activate it, it is only taking the gold ingots and ignoring the rest of the materials... resulting in a gold helmet factory.  I tried increasing the ingots requirements for gold helmet in the config, but this resulted in the diamond pickaxe smithy. Maybe i'm doing something wrong?

**Comment by gmlaxfanatic** [comment]
Good catch. It appears the code doesn't look at extra items once one if found that matches that specified for a factory in the config.
