### ISSUE TITLE
Issue with Factory Mod, Diamond Cauldron

### ISSUE THREAD

**Issue by Random902** [gmlaxfanatic/FactoryMod#5]
Having an issue with using diamond cauldron to generate XP bottles. Using recipe #2, it tells me to put in 64 nether wart, when there is already 64 in there. I think it's an issue with the block ID, perhaps you used the plant ID rather than item?

**Comment by gmlaxfanatic** [comment]
Thanks for the report! See here for my previous response https://github.com/gmlaxfanatic/FactoryMod/issues/6
