### ISSUE TITLE
Recipe 'Brew XP Bottles - 2' doesn't recognise netherwart

### ISSUE THREAD

**Issue by hawtre** [gmlaxfanatic/FactoryMod#6]
Chest is filled with the correct ingredients (in the same order as listed as well, if that changes anything). When clicking the furnace I'm told "You need all of the following: 64 Nether Warts."
When removing the melons, for example, that message changes to include the melons, but no matter what I do with the nether warts (move them to a different slot, or just remove them from the chest) I still get told that I'm missing 64 nether warts.

Is the correct block id being used?
![factory1](https://f.cloud.github.com/assets/3225104/562075/ebc49cd8-c49f-11e2-8a71-3e14388ede72.png)
![factory3](https://f.cloud.github.com/assets/3225104/562077/ebc71210-c49f-11e2-9f28-798f3fe943f1.png)
![factory2](https://f.cloud.github.com/assets/3225104/562076/ebc24a5a-c49f-11e2-9eef-4abb71c3eb05.png)

**Comment by gmlaxfanatic** [comment]
Thanks for the report, I think netherwart may behavior weirdly in bukkit so its likely a problem there. I'll try to look into it soon but may not get to it until wednesday since I am vacation.
